### ISSUE TITLE
Where is the gradients.zip file?

### ISSUE THREAD

**Issue by matheustavares** [HugoBDesigner/love.gradient#2]
I really liked your lib but I can't find the gradients.zip file required by the gradient.lua to work. Did you removed it from the repository?

**Comment by HugoBDesigner** [comment]
I'm sorry for the inconvenience. I must have deleted it by accident. It's been reuploaded now.

**Comment by matheustavares** [comment]
Thanks! :) But now I'm not being able to unzip the file. It gives an error. Could you confirm if this is an error of mine or if the file is, for some reason, corrupted?

**Comment by HugoBDesigner** [comment]
I'm so sorry again! Turns out the first uploaded file was corrupted for some reason, so I had to find a working copy being hosted elsewhere. I just tested to make sure, and it _should_ be working now.
